name: Scheduled GitHub Repo Settings Scan

on:
  push:
    branches:
      - arc-74_fix_repo_settings_auditscript
  schedule:
    # Run on 1st and 15th of every month at 08:00
    - cron: "0 8 1,15 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install -r audit-github-repo-settings_requirements.txt

      - name: Scan develop branches
        env:
          DEVOPS_TOKEN: ${{ secrets.DEVOPS_TOKEN }}
        run: |
          ./audit-github-repo-settings.py \
            --branches develop \
            --github-token "$DEVOPS_TOKEN" \
            --open-github-issues \
            --organizations usdot-fhwa-stol usdot-fhwa-ops usdot-jpo-ode

      - name: Scan master branches
        env:
          DEVOPS_TOKEN: ${{ secrets.DEVOPS_TOKEN }}
        run: |
          ./audit-github-repo-settings.py \
            --branches master \
            --github-token "$DEVOPS_TOKEN" \
            --open-github-issues \
            --organizations usdot-fhwa-stol usdot-fhwa-ops usdot-jpo-ode

      - name: Scan main branches
        env:
          DEVOPS_TOKEN: ${{ secrets.DEVOPS_TOKEN }}
        run: |
          ./audit-github-repo-settings.py \
            --branches main \
            --github-token "$DEVOPS_TOKEN" \
            --open-github-issues \
            --organizations usdot-fhwa-stol usdot-fhwa-ops usdot-jpo-ode