on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install -r github2jira_requirements.txt

      - name: Run github2jira.py
        env:
          DEVOPS_GITHUB_TOKEN: ${{ secrets.DEVOPS_GITHUB_TOKEN }}
          GITHUB_ISSUE_NUMBER: "${{ github.event.issue.number }}"
          JIRA_BOARD: "DEV board"
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
        run: |
          ./github2jira.py \
            --github-issue-number "$GITHUB_ISSUE_NUMBER" \
            --github-repo "$GITHUB_REPOSITORY" \
            --github-token "$DEVOPS_GITHUB_TOKEN" \
            --jira-board "$JIRA_BOARD" \
            --jira-email "$JIRA_EMAIL" \
            --jira-server "$JIRA_URL" \
            --jira-token "$JIRA_TOKEN"
